# Generated by Django 4.2.5 on 2023-10-06 21:02

import book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_borrowedbook_borrow_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbook',
            name='return_date',
            field=models.DateTimeField(blank=True, default=book.models.in_three_days, null=True),
        ),
    ]
